BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "b650d4u"
BBFILE_PATTERN_b650d4u = "^${LAYERDIR}/"
BBFILE_PRIORITY_b650d4u = "5"
LAYERSERIES_COMPAT_b650d4u = "wrynose scarthgap nanbield Mickledore langdale kirkstone"
